### ISSUE TITLE
Empty password does not pass even with passthrough_auth = "enabled_plain" and auth_type = "trust"

### ISSUE THREAD

**Issue by sandangel** [pgdogdev/pgdog#155]
Having error:

```sh
fe_sendauth: no password supplied
```

When using empty password even when settings those 2 values

```toml
# https://github.com/pgdogdev/pgdog/blob/main/pgdog.toml
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 5_000
openmetrics_port = 9930
query_timeout = 1_000
checkout_timeout = 1_000
connect_timeout = 1_000
idle_timeout = 30_000
prepared_statements = "extended"
passthrough_auth = "enabled_plain"
default_pool_size = 100
workers = 10
min_pool_size = 1
pooler_mode = "transaction"
load_balancing_strategy = "least_active_connections"
auth_type = "trust"

[admin]
user = "pgdog"
password = "pgdog"

[[databases]]
name = "postgres"
host = "localhost"
role = "primary"
port = 5432

[[databases]]
name = "foo"
host = "localhost"
role = "primary"
port = 5432

[[databases]]
name = "foo"
host = "localhost"
port = 5433
role = "replica"

[[databases]]
name = "bar"
host = "localhost"
role = "replica"
port = 5433

[tcp]
retries = 3
time = 1000
interval = 1000
user_timeout = 1000

```

users.toml

```toml
[[users]]
name = "user1"
database = "foo"
password = ""
server_password = ""

[[users]]
name = "user2"
database = "bar"
password = ""
server_password = ""

[[users]]
name = "postgres"
database = "postgres"
password = ""
server_password = ""
```

I'm already using Auth Proxy with auto iam, so the password should be empty.
