### ISSUE TITLE
Cannot execute INSERT in a read-only transaction

### ISSUE THREAD

**Issue by sandangel** [pgdogdev/pgdog#157]
```sh
 sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.ReadOnlySQLTransactionError'>: cannot execute INSERT in a read-only transaction

```

I'm running stress test for my system with pgdog, it has this issue with some requests. Not always though.

```toml
# https://github.com/pgdogdev/pgdog/blob/main/pgdog.toml
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 5_000
openmetrics_port = 9930
query_timeout = 1_000
checkout_timeout = 1_000
connect_timeout = 1_000
idle_timeout = 30_000
prepared_statements = "extended"
passthrough_auth = "enabled_plain"
default_pool_size = 100
workers = 10
min_pool_size = 1
pooler_mode = "transaction"
load_balancing_strategy = "least_active_connections"
auth_type = "trust"

[admin]
user = "pgdog"
password = "pgdog"

[[databases]]
name = "postgres"
host = "localhost"
role = "primary"
port = 5432

[[databases]]
name = "foo"
host = "localhost"
role = "primary"
port = 5432

[[databases]]
name = "foo"
host = "localhost"
port = 5433
role = "replica"

[[databases]]
name = "bar"
host = "localhost"
role = "replica"
port = 5433

[tcp]
retries = 3
time = 1000
interval = 1000
user_timeout = 1000
```
