### ISSUE TITLE
Pgedge support

### ISSUE THREAD

**Issue by rocinant3** [pgdogdev/pgdog#52]
[Pgedge](https://www.pgedge.com/) is a postgres + multi-master replication extension.

Problem: pgdog can't connect to node

Pgdog log:
```
2025-03-23T18:13:48.713379Z INFO pgdog::backend::pool::monitor: creating new healthcheck connection [0.0.0.0:5432, defaultdb]
2025-03-23T18:13:48.728493Z ERROR pgdog::backend::pool::monitor: healthcheck error: unsupported authentication algorithm [0.0.0.0:5432, defaultdb]
```

Docker log:
```
postgres-n1-1  | 2025-03-23 18:16:48 UTC [74]: [1-1] user=admin,db=defaultdb,app=[unknown],client=192.168.117.1 LOG:  could not receive data from client: Connection reset by peer
```

docker-compose.yml:

```
services:
  postgres-n1:
    image: pgedge/pgedge:latest
    ports:
      - "5432:5432"
    environment:
      - "NODE_NAME=n1"
      - "PGDATA=/data/pgdata"
    volumes:
      - "./db.json:/home/pgedge/db.json"
      - "./data/n1:/data"
    networks:
      - database

  postgres-n2:
    image: pgedge/pgedge:latest
    ports:
      - "5433:5432"
    environment:
      - "NODE_NAME=n2"
      - "PGDATA=/data/pgdata"
    volumes:
      - "./db.json:/home/pgedge/db.json"
      - "./data/n2:/data"
    networks:
      - database

networks:
  database:
```

db.json
```
{
  "name": "defaultdb",
  "port": 5432,
  "options": ["autoddl:enabled"],
  "nodes": [
    {
      "name": "n1",
      "region": "us-east-1",
      "hostname": "postgres-n1"
    },
    {
      "name": "n2",
      "region": "us-east-2",
      "hostname": "postgres-n2"
    }
  ],
  "users": [
    {
      "username": "app",
      "password": "0Osh8bqE5EokT3I3Z78MQ344",
      "superuser": false,
      "service": "postgres",
      "type": "application"
    },
    {
      "username": "admin",
      "password": "uFR44yr69C4mZa72g3JQ37GX",
      "superuser": true,
      "service": "postgres",
      "type": "admin"
    },
    {
      "username": "pgedge",
      "password": "z1Zsku10a91RS526jnVrLC39",
      "superuser": true,
      "service": "postgres",
      "type": "internal_admin"
    },
  ]
}
```

pgdog.toml
```
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 5_000

[[databases]]
name = "defaultdb"
host = "0.0.0.0"
role = "primary"
user = "admin"
password = "uFR44yr69C4mZa72g3JQ37GX"
port = 5432


[[databases]]
name = "defaultdb"
host = "0.0.0.0"
role = "primary"
user = "admin"
password = "uFR44yr69C4mZa72g3JQ37GX"
port = 5433
```

users.toml
```
[[users]]
database = "defaultdb"
name = "admin"
password = "uFR44yr69C4mZa72g3JQ37GX"
```

PS: pgcat [works well](https://github.com/pgEdge/pgedge-docker/tree/main) with pgedge
