### ISSUE TITLE
Error: closing out of sync server connection

### ISSUE THREAD

**Issue by rocinant3** [pgdogdev/pgdog#57]
An error occurs when trying to execute a simple query. This is a bug that appeared after the last update

Log:
```
pgdog-1  | 2025-03-26T18:03:13.299891Z  INFO client connected [ip2:2807]
pgdog-1  | 2025-03-26T18:03:13.369646Z DEBUG SELECT * FROM my_table
pgdog-1  | 2025-03-26T18:03:13.369815Z DEBUG client paired with {ip}:5432, db_name [0.0888ms]
pgdog-1  | 2025-03-26T18:03:13.369895Z DEBUG preparing "__pgdog_1" [{ip}:5432, db_name]
pgdog-1  | 2025-03-26T18:03:13.447813Z DEBUG 
pgdog-1  |                     SELECT
pgdog-1  |                         current_setting('jit') AS cur,
pgdog-1  |                         set_config('jit', 'off', false) AS new
pgdog-1  |                     
pgdog-1  | 2025-03-26T18:03:13.517413Z  INFO closing out of sync server connection [ip:5432, db_name]
pgdog-1  | 2025-03-26T18:03:13.517510Z  INFO client disconnected [ip2:2807]
```

Python log:
```
  File "asyncpg/protocol/protocol.pyx", line 165, in prepare
asyncpg.exceptions.PostgresSystemError: server connection is not synchronized
```

pgdog.toml
```
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 100

[[databases]]
...skip
role = "primary"

[[databases]]
...skip
role = "replica"
```

**Comment by levkk** [comment]
I've been adding a few things, could you give me commit hash you're on?

**Comment by rocinant3** [comment]
So, the problem is not in the latest update, sorry. I was confused that pgpool2 works without errors in the same conditions. I suspect that the problem lies somewhere in the replication, maybe the two nodes are not fully synchronized, but then why does pgpool work without errors?

docker:
```
services:
  master:
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=nopassword
    ports:
      - "5432:5432"
    volumes:
      - ./pg_master_data:/bitnami/postgresql

  slave:
    image: "bitnami/postgresql:latest"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=nopassword
    depends_on:
      - master
    ports:
      - "5433:5432"
    volumes:
      - ./pg_slave_data:/bitnami/postgresql

volumes:
  pg_master_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/master"
  pg_slave_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./data/slave"
```

code:
```
import asyncio
import asyncpg
import datetime

class DbConn:
    def __init__(self, dsn: str):
        self.connection: asyncpg.Connection | None = None
        self.dsn = dsn

    async def __aenter__(self):
        self.connection = await asyncpg.connect(self.dsn)
        return self.connection

    async def __aexit__(self, *_):
        if self.connection:
            await self.connection.close()

async def main():
    async with DbConn('postgresql://user:nopassword@0.0.0.0:6432/db') as conn:
        print(await conn.fetch('SELECT * FROM user'))
```

conf:
```
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 100


[[databases]]
name = "db"
user = "user"
password = "nopassword"
host = "0.0.0.0"
port = 5432
role = "primary"

[[databases]]
name = "db"
user = "user"
password = "nopassword"
host = "0.0.0.0"
port = 5433
role = "replica"
```
